import type { BehaviouralAssumption } from '../types';

export const BEHAVIOURAL_ASSUMPTIONS: BehaviouralAssumption[] = [
  {
    id: 'assumption.general.peoplePerImmigrationPercent',
    description: 'General simulator conversion from the abstract immigration-rate input to annual population increase.',
    centralValue: 100_000,
    plausibleLow: 100_000,
    plausibleHigh: 100_000,
    unit: 'people per immigration input point',
    supportingEvidence: 'Phase 1A audit: migrated existing hard-coded value; authoritative source pending.',
    confidence: 'low',
    affectedRelationships: ['population growth', 'housing demand', 'service pressure'],
    formulaLocation: 'src/simulation/World.ts',
    materiality: 'high',
    calibrationStatus: 'uncalibrated',
    reviewerNotes: 'Do not interpret as an observed statistic until the immigration-rate control is redefined.',
  },
  {
    id: 'assumption.general.baseEconomicGrowth',
    description: 'Base economic-growth value used before policy, entity, event and feedback adjustments.',
    centralValue: 2,
    plausibleLow: 2,
    plausibleHigh: 2,
    unit: 'percent-like growth units',
    supportingEvidence: 'Phase 1A audit: existing model value; ABS/RBA/Treasury review pending.',
    confidence: 'low',
    affectedRelationships: ['economic growth', 'government revenue', 'success score'],
    formulaLocation: 'src/simulation/World.ts',
    materiality: 'high',
    calibrationStatus: 'uncalibrated',
    reviewerNotes: 'Current value is preserved to avoid output changes.',
  },
  {
    id: 'assumption.immigration.migrantWorkingAgeShare',
    description: 'Share of migrant inflow assumed to be working age in the immigration model.',
    centralValue: 78,
    plausibleLow: 78,
    plausibleHigh: 78,
    unit: 'percent',
    supportingEvidence: 'Phase 1A audit: migrated existing default; ABS/Home Affairs age-profile review pending.',
    confidence: 'low',
    affectedRelationships: ['labour supply', 'dependency ratio', 'service demand'],
    formulaLocation: 'src/topics/immigration/model.ts',
    materiality: 'high',
    calibrationStatus: 'uncalibrated',
    reviewerNotes: 'Should later be segmented by visa/status and age.',
  },
  {
    id: 'assumption.immigration.workforceParticipation',
    description: 'Workforce participation assumption used in the immigration current path.',
    centralValue: 67,
    plausibleLow: 67,
    plausibleHigh: 67,
    unit: 'percent',
    supportingEvidence: 'Phase 1A audit: migrated existing default; ABS Labour Force review pending.',
    confidence: 'low',
    affectedRelationships: ['labour supply', 'tax revenue', 'construction capacity'],
    formulaLocation: 'src/topics/immigration/model.ts',
    materiality: 'high',
    calibrationStatus: 'uncalibrated',
    reviewerNotes: 'Observed total participation and migrant-group participation should be separated in Phase 1C.',
  },
  {
    id: 'assumption.immigration.productivityGrowth',
    description: 'Productivity-growth assumption used by immigration business-capacity calculations.',
    centralValue: 1.2,
    plausibleLow: 1.2,
    plausibleHigh: 1.2,
    unit: 'percent/year',
    supportingEvidence: 'Phase 1A audit: migrated existing default; ABS/Treasury review pending.',
    confidence: 'low',
    affectedRelationships: ['business capacity', 'living standards proxy'],
    formulaLocation: 'src/topics/immigration/model.ts',
    materiality: 'high',
    calibrationStatus: 'uncalibrated',
    reviewerNotes: 'Do not treat as a forecast until sourced.',
  },
  {
    id: 'assumption.immigration.averageTaxPerWorker',
    description: 'Average tax contribution per worker in the immigration model.',
    centralValue: 28_000,
    plausibleLow: 22_000,
    plausibleHigh: 36_000,
    unit: 'AUD/worker/year',
    supportingEvidence: 'Phase 1A audit: migrated existing default; ATO/Treasury/PBO review pending.',
    confidence: 'low',
    affectedRelationships: ['tax revenue', 'federal budget pressure'],
    formulaLocation: 'src/topics/immigration/model.ts',
    materiality: 'high',
    calibrationStatus: 'uncalibrated',
    reviewerNotes: 'Should later vary by income, employment status and visa/duration.',
  },
  {
    id: 'assumption.immigration.governmentSpendingPerPerson',
    description: 'Average government spending/service cost per person in the immigration model.',
    centralValue: 23_000,
    plausibleLow: 18_000,
    plausibleHigh: 32_000,
    unit: 'AUD/person/year',
    supportingEvidence: 'Phase 1A audit: migrated existing default; budget/AIHW/education review pending.',
    confidence: 'low',
    affectedRelationships: ['service cost', 'federal budget pressure'],
    formulaLocation: 'src/topics/immigration/model.ts',
    materiality: 'high',
    calibrationStatus: 'uncalibrated',
    reviewerNotes: 'Should later vary by age and service category.',
  },
  {
    id: 'assumption.immigration.infrastructureCostPerAdditionalPerson',
    description: 'Infrastructure cost per additional person used in state-pressure calculations.',
    centralValue: 13_000,
    plausibleLow: 13_000,
    plausibleHigh: 13_000,
    unit: 'AUD/person',
    supportingEvidence: 'Phase 1A audit: migrated existing default; Infrastructure Australia/state review pending.',
    confidence: 'low',
    affectedRelationships: ['infrastructure pressure', 'state budget pressure'],
    formulaLocation: 'src/topics/immigration/model.ts',
    materiality: 'high',
    calibrationStatus: 'uncalibrated',
    reviewerNotes: 'Needs asset-class/location/lags before calibration.',
  },
  {
    id: 'assumption.immigration.socialCohesionSensitivity',
    description: 'Sensitivity of social cohesion risk to housing/service pressure.',
    centralValue: 45,
    plausibleLow: 25,
    plausibleHigh: 70,
    unit: '0-100 index',
    supportingEvidence: 'Phase 1A audit: exploratory placeholder; expert review required.',
    confidence: 'exploratory',
    affectedRelationships: ['social cohesion risk', 'winners and losers', 'commentary'],
    formulaLocation: 'src/topics/immigration/model.ts',
    materiality: 'high',
    calibrationStatus: 'uncalibrated',
    reviewerNotes: 'Politically sensitive; keep low-confidence visible.',
  },
  {
    id: 'assumption.immigration.environmentalPressurePerPerson',
    description: 'Environmental intensity used by immigration environmental pressure index.',
    centralValue: 1,
    plausibleLow: 0.6,
    plausibleHigh: 1.5,
    unit: 'index',
    supportingEvidence: 'Phase 1A audit: exploratory placeholder; DCCEEW/AEMO review pending.',
    confidence: 'exploratory',
    affectedRelationships: ['environmental pressure'],
    formulaLocation: 'src/topics/immigration/model.ts',
    materiality: 'medium',
    calibrationStatus: 'uncalibrated',
    reviewerNotes: 'Split into emissions, energy, water and land-use channels later.',
  },
];

export function getBehaviouralAssumption(id: string) {
  const assumption = BEHAVIOURAL_ASSUMPTIONS.find((item) => item.id === id);
  if (!assumption) throw new Error(`Unknown behavioural assumption: ${id}`);
  return assumption;
}
